# Generated by Django 2.0.7 on 2018-07-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('rowkey', models.AutoField(db_column='RowKey', primary_key=True, serialize=False)),
                ('categoryid', models.CharField(blank=True, db_column='categoryId', max_length=255, null=True)),
                ('categoryname', models.CharField(blank=True, db_column='categoryName', max_length=255, null=True)),
                ('categorydetail', models.CharField(blank=True, db_column='categoryDetail', max_length=255, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
    ]
